import datetime as dt

from sqlalchemy import Column, Integer, String, Text, DateTime, ForeignKey, Float
from sqlalchemy.orm import relationship

from app.database import Base


class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    full_name = Column(String(120), nullable=False)
    email = Column(String(150), unique=True, index=True, nullable=False)
    hashed_password = Column(String(255), nullable=False)
    created_at = Column(DateTime, default=dt.datetime.utcnow)

    resumes = relationship("Resume", back_populates="owner", cascade="all, delete-orphan")
    analyses = relationship("Analysis", back_populates="owner", cascade="all, delete-orphan")
    cover_letters = relationship("CoverLetter", back_populates="owner", cascade="all, delete-orphan")


class Resume(Base):
    """An uploaded resume OR a resume generated by the builder feature."""
    __tablename__ = "resumes"

    id = Column(Integer, primary_key=True, index=True)
    owner_id = Column(Integer, ForeignKey("users.id"), nullable=False)

    source = Column(String(20), default="upload")  # "upload" | "builder"
    filename = Column(String(255), nullable=True)
    file_path = Column(String(500), nullable=True)   # original upload path, if any
    generated_pdf_path = Column(String(500), nullable=True)  # builder output, if any
    raw_text = Column(Text, nullable=False)

    created_at = Column(DateTime, default=dt.datetime.utcnow)

    owner = relationship("User", back_populates="resumes")
    analyses = relationship("Analysis", back_populates="resume", cascade="all, delete-orphan")


class Analysis(Base):
    """Result of running the RAG analyzer pipeline on a resume vs a job description."""
    __tablename__ = "analyses"

    id = Column(Integer, primary_key=True, index=True)
    owner_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    resume_id = Column(Integer, ForeignKey("resumes.id"), nullable=False)

    job_description = Column(Text, nullable=False)
    match_score = Column(Float, nullable=True)
    strengths = Column(Text, nullable=True)
    gaps = Column(Text, nullable=True)
    suggestions = Column(Text, nullable=True)
    weaknesses = Column(Text, nullable=True)
    matching_skills = Column(Text, nullable=True)
    missing_skills = Column(Text, nullable=True)
    upskilling_resources = Column(Text, nullable=True)
    detailed_review = Column(Text, nullable=True)
    raw_feedback = Column(Text, nullable=True)

    created_at = Column(DateTime, default=dt.datetime.utcnow)

    owner = relationship("User", back_populates="analyses")
    resume = relationship("Resume", back_populates="analyses")


class CoverLetter(Base):
    __tablename__ = "cover_letters"

    id = Column(Integer, primary_key=True, index=True)
    owner_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    resume_id = Column(Integer, ForeignKey("resumes.id"), nullable=True)

    job_description = Column(Text, nullable=False)
    company_name = Column(String(200), nullable=True)
    content = Column(Text, nullable=False)
    generated_pdf_path = Column(String(500), nullable=True)

    created_at = Column(DateTime, default=dt.datetime.utcnow)

    owner = relationship("User", back_populates="cover_letters")
